# https://docs.readthedocs.io/en/latest/yaml-config.html
version: 2

formats:
  - htmlzip
  - epub

build:
  image: latest

python:
  version: 3
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
