name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - "*"
  schedule:
    # Daily at 05:47
    - cron: '47 5 * * *'

env:
  PACKAGE_NAME: 'qtrio'

jobs:
  Windows:
    name: 'Windows (${{ matrix.python }}, ${{ matrix.qt_library }})'
    timeout-minutes: 20
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8']
        qt_library: ['PySide2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
          architecture: '${{ matrix.arch }}'
      - name: Run tests
        run: ./ci.sh
        shell: bash
        env:
          # Should match 'name:' up above
          JOB_NAME: 'Windows (${{ matrix.python }}, ${{ matrix.arch }}, ${{ matrix.qt_library }})'
          INSTALL_EXTRAS: '[${{ matrix.qt_library }},tests]'

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - Windows
    steps:
      - name: This
        shell: python
        run: |
          import this
