name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - "*"
  schedule:
    # Daily at 05:47
    - cron: '47 5 * * *'

jobs:
  Builds:
    name: '${{ matrix.name }}'
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.8'
            name: 'Build source'
            pep517_option: '--source'
          - python: '3.8'
            name: 'Build binary'
            pep517_option: '--binary'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
      - name: Build
        run: |-
          python -m venv venv
          venv/bin/python -m pip install --quiet --upgrade pip setuptools wheel
          venv/bin/python -m pip install --quiet --upgrade pep517
          venv/bin/python -m pip list
          venv/bin/python -m pip freeze
          venv/bin/python -m pep517.build ${{ matrix.pep517_option }} --out-dir dist/ .
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  Checks:
    name: '${{ matrix.name }}'
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.8'
            check_docs: '1'
            name: 'Check docs'
          - python: '3.8'
            check_formatting: '1'
            name: 'Check formatting'
          - python: '3.8'
            check_type_hints: '1'
            name: 'Check type hints'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
      - name: Run tests
        run: ./ci.sh
        env:
          CHECK_DOCS: '${{ matrix.check_docs }}'
          CHECK_FORMATTING: '${{ matrix.check_formatting }}'
          CHECK_TYPE_HINTS: '${{ matrix.check_type_hints }}'
          # Should match 'name:' up above
          JOB_NAME: '${{ matrix.name }}'
          # TODO: needs some Qt library but I'm not clear the implications of
          #       choosing one over the other
          INSTALL_EXTRAS: '[pyside2,checks,docs]'

  Windows:
    name: 'Windows (${{ matrix.python }}, ${{ matrix.arch }}, ${{ matrix.qt_version }}, ${{ matrix.qt_library }})'
    timeout-minutes: 20
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6', '3.7', '3.8']
        arch: ['x86', 'x64']
        qt_version: ['~=5.14.0', '~=5.15.0']
        qt_library: ['PyQt5', 'PySide2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
          architecture: '${{ matrix.arch }}'
      - name: Run tests
        run: ./ci.sh
        shell: bash
        env:
          # Should match 'name:' up above
          JOB_NAME: 'Windows (${{ matrix.python }}, ${{ matrix.arch }}, ${{ matrix.qt_version }}, ${{ matrix.qt_library }})'
          INSTALL_EXTRAS: '[${{ matrix.qt_library }},tests]'
          QT_LIBRARY_AND_VERSION: '${{ matrix.qt_library }}${{ matrix.qt_version }}'
          QT_QPA_PLATFORM: 'offscreen'
      - name: Download
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - name: Extract
        run: Expand-Archive ngrok.zip
      - name: Auth
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      - name: Create Tunnel
        run: .\ngrok\ngrok.exe tcp 3389

  Ubuntu:
    name: 'Ubuntu (${{ matrix.python }}, ${{ matrix.qt_version }}, ${{ matrix.qt_library }})'
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    container: 'docker://python:${{ matrix.python }}-buster'
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6', '3.7', '3.8']
        qt_version: ['~=5.14.0', '~=5.15.0']
        qt_library: ['PyQt5', 'PySide2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
      - name: Install Qt5 dependencies
        run: |
          apt-get update --yes
          apt-get install --yes libgl1
      - name: Install Linux test dependencies
        run: |
          apt-get update --yes
          apt-get install --yes libgl1-mesa-dev xvfb x11-utils libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
      - name: Run tests
        run: ./ci.sh
        env:
          # Should match 'name:' up above
          JOB_NAME: 'Ubuntu (${{ matrix.python }}, ${{ matrix.qt_version }}, ${{ matrix.qt_library }})'
          INSTALL_EXTRAS: '[${{ matrix.qt_library }},tests]'
          QT_LIBRARY_AND_VERSION: '${{ matrix.qt_library }}${{ matrix.qt_version }}'

  macOS:
    name: 'macOS (${{ matrix.python }}, ${{ matrix.qt_version }}, ${{matrix.qt_library}})'
    timeout-minutes: 10
    runs-on: 'macos-latest'
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6', '3.7', '3.8']
        qt_version: ['~=5.14.0', '~=5.15.0']
        qt_library: ['PyQt5', 'PySide2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
      - name: Run tests
        run: ./ci.sh
        env:
          # Should match 'name:' up above
          JOB_NAME: 'macOS (${{ matrix.python }}, ${{ matrix.qt_version }}, ${{matrix.qt_library}})'
          INSTALL_EXTRAS: '[${{ matrix.qt_library }},tests]'
          QT_LIBRARY_AND_VERSION: '${{ matrix.qt_library }}${{ matrix.qt_version }}'

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - Builds
      - Checks
      - Windows
      - Ubuntu
      - macOS
    steps:
      - name: This
        shell: python
        run: |
          import this
